### PR TITLE
Add a makefile to simplify the build process

### PR DESCRIPTION
**Pull request by Jafaral**
makefile to build fg3d 

This will makes it easy to build your application. I tried to make it generic enough so that you can tweak it and use it in your other projects if you wish.

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

### CODE REVIEW

**Comment by Jafaral** [comment]
@shawnfratis there you go. This addresses #1

**Comment by Jafaral** [comment]
You should be able to push merge and get this integrated with your code.

**Comment by shawnfratis** [comment]
Great! :) Thank you very much!

**Comment by shawnfratis** [comment]
Also, you should try using this on the one I have called fg3d_lite. That's
the one I've done the most recent changes to. Sorry for any confusion, it
was just easier for me to split them up. Thanks again

**Pull request merged**
